name: Android CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Secret to File
        uses: MobileDevOps/secret-to-file-action@v1.0.0
        with:
          base64-encoded-secret: ${{ secrets.AUTH_CONFIG_SINGLE_ACCOUNT_JSON }}
          filename: "auth_config_single_account.json"
          working-directory: "./app/src/main/res/raw/"

      - name: Cat
        run: cat ./app/src/main/res/raw/auth_config_single_account.json
      
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: files.apk
          path: ./app/build/outputs/apk/debug/app-debug.apk

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: secret
          path: ./app/src/main/res/raw/auth_config_single_account.json
